repos:
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile=black"]
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        language_version: python3.12
  - repo: local
    hooks:
      - id: ui-new-lint
        name: ui-new eslint
        entry: bash -c 'cd ui-new && npm run lint'
        language: system
        pass_filenames: false
      - id: ui-new-format
        name: ui-new prettier
        entry: bash -c 'cd ui-new && npm run format:check'
        language: system
        pass_filenames: false